# kickstart travis.
language: java
jdk:
  - oraclejdk8
  - oraclejdk7
  - openjdk6
#before_install: sudo pip install codecov
#after_success: codecov

# need to override travis 'install' since it will try gpg sign and fail.
#install: mvn clean package -DskipTests=true

#branches:
#  except:
#      - mvn-repo
notifications:
  email:
    - vidyasagarkarnati@yahoo.com